api:
  base-path: /api/v1
oauth:
  client:
    kakao:
      client-id: {client-id}
      token-uri: https://kauth.kakao.com/oauth/token
      logout-uri: https://kauth.kakao.com/oauth/logout
      logout-redirect-uri: http://localhost:8080
---
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/static/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: {client-id}
            client-secret: {client-secret}
            redirect-uri: http://localhost:8080/auth/code/google/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: {client-id}
            client-secret: {client-secret}
            redirect-uri: http://localhost:8080/auth/code/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id